-- Legacy sample-data.sql replaced by database/init-and-seed.sql.
-- The canonical seed now uses the new CSV-aligned schema:
-- client_id, order_id, order_date, delivery_date, carrier, origin_city,
-- destination_city, status, sku, product_category, quantity, unit_price_usd,
-- order_value_usd, is_promo, promo_discount_pct, region, warehouse.
